### ISSUE TITLE
filter by multiple tags

### ISSUE THREAD

**Issue by gvoysey** [davep/pinboard.el#11]
One of the real gems of pinboard is that you can search by multiple tags to filter collections more narrowly. 

the `T` keybinding appears to treat its entire input as one tag, even if that input is a collection of comma- or whitespace- delimited tags.   So where I can go to `pinboard.in/u:MYUSER/t:TAG1/t:TAG2` to get the union of those tags as a search result, i cannot spell this in `pinboard.el` as `T` `TAG1, TAG2` or `T` `TAG1 TAG2`. 

this would be very handy.

**Comment by davep** [comment]
From the README:

![Screenshot 2020-06-01 at 16 27 01](https://user-images.githubusercontent.com/28237/83424775-cb037200-a424-11ea-8611-51eab87c8228.png)

The idea being that `pinboard-tagged` (bound to <kbd>T</kbd> by default) starts a brand new tag filtering "session", and `pinboard-extend-tagged` (bound to <kbd>t</kbd> by default) adds a tag to the list of tags to combine and search for.

Is that the sort of thing you mean?

**Comment by gvoysey** [comment]
yup! i'm an idiot. :)  

thanks. that's a lot nicer than parsing a string-that-should-be-a-list.

**Comment by davep** [comment]
No worries; it's easily missed and always good to ask. :)
