### ISSUE TITLE
Empty buffer showing only headers.

### ISSUE THREAD

**Issue by tenpast** [davep/pinboard.el#12]
Hi, 
First, thank you for a very useful mode, I've used it for a while with excellent results!

I had not used it for quite a while and today I tried it (M-x pinboard) and got an empty buffer showing only the column headers. In Emacs's *Messages* buffer, I could see the following: 
```
pinboard-call: Error ’JSON readtable error: 65279’ handling reply from Pinboard: ﻿[{... 
```
...followed by what appears to be a full list of all my bookmarks, with descriptions and tags.

Do you have any idea what could be causing this issue?

Pinboard configuration in my init file is:

```
    (use-package pinboard
      :ensure t) 
```

Thank you for your help.

**Comment by davep** [comment]
This seems to be [a problem with the Pinboard API itself](https://twitter.com/damienrajon/status/1275713849665208320).

**Comment by tenpast** [comment]
Thanks for the quick response. I should have checked Pinboard's Twitter before opening an issue here. 

I will go ahead and close this issue.

**Comment by davep** [comment]
For what it's worth, it wasn't obvious to me from their twitter feed either, I had to do a search of Twitter and found it via that linked tweet. I'm glad you asked here as now I'm aware of it and can keep checking. :)

**Comment by tenpast** [comment]
Indeed, I didn't realize this when I responded. After sending the last message I looked through their Twitter feed and could not find any mention to it either!

**Comment by tenpast** [comment]
Hello again! I received an email back from Pinboard:

> The issue is a byte-order mark; is there any way you can strip whitespace
> before parsing JSON input? I'm trying to reproduce and fix this bug in my
> dev environment, but so far can't find where it's coming from. It started
> happening after a Ubuntu update, with no code changes.

I'm not sure if it's easy/worthwhile check for whitespace and strip before parsing. Perhaps it's just a matter of being patient while the issue is fixed at Pinboard.

**Comment by davep** [comment]
Yeah, looking at further chat on Twitter last night, it's looking like it's going to be tricky for him to track down and fix right now. I'll see about adding a check/correct in `pinboard.el` this evening after work (or earlier if I have a boring work moment and want to hack some Elisp ;)).

**Comment by davep** [comment]
I suspect there's a smarter way of doing this that relates to buffer coding, utf-8/16/something, etc, but for now ab2bd1627af89ac816b58615f3e969fb73f95072 seems to do the job of getting things working again.

I've not tagged it for stable just yet, but if you use non-stable melpa this change should turn up soon. And if this situation with Pinboard carries on for too long I'll make this a stable release (and perhaps try and find out a better way of doing this).

Let's keep this issue open for now.

**Comment by tenpast** [comment]
Yes, I confirm your temporary solution works for me too. Much appreciated, and apologies for the late reply. Thank you!

**Comment by davep** [comment]
No apology needed, I appreciate the update.

**Comment by tenpast** [comment]
Hi, just a quick follow-up. I received an email from Pinboard today telling me this BOM was fixed about 10 days ago. 

Thanks again for your quick patch to maintain the functionality of pinboard.el!

**Comment by davep** [comment]
Thanks for the update, and for letting me know in the first place.
