### ISSUE TITLE
optionally persist *Pinboard pin* minibuffer

### ISSUE THREAD

**Issue by gvoysey** [davep/pinboard.el#15]
i'm not sure if this is a pinboard feature or an emacs configuration option, so please close if this is irrelevant. 

currently `pinboard-view`:
- opens a minibuffer with the details of the currently highlighted pin
- shifts focus to that minibuffer
- is dismissed with <C-g>

I'd like to have a way to open a new window in the frame without shifting focus to it, which provides the details of the currently highlighted pin and updates as i navigate the main *Pinboard* buffer.  

How might that happen?

**Comment by davep** [comment]
Curious, I don't get the focus shift here. If I invoke [`pinboard-view`](https://github.com/davep/pinboard.el/blob/d426f9d2ebec5f907c8a89d6b38ccbcb13750d4f/pinboard.el#L341) (via [the default mapping of <kbd>SPC</kbd>](https://github.com/davep/pinboard.el/blob/d426f9d2ebec5f907c8a89d6b38ccbcb13750d4f/pinboard.el#L697)) it opens the view buffer but keeps focus in the pin list buffer; navigating to another pin and hitting <kbd>SPC</kbd> again updates with the details of the new pin.

Perhaps this is a configuration option that pertains to help buffers? [I use `with-help-window`](https://github.com/davep/pinboard.el/blob/d426f9d2ebec5f907c8a89d6b38ccbcb13750d4f/pinboard.el#L345) to show the details.

**Comment by gvoysey** [comment]
C-h m gives this horror show, so perhaps i've got some bisecting in my future: 

```Enabled minor modes: Anzu Async-Bytecomp-Package Auto-Composition Auto-Compression
Auto-Encryption Blink-Cursor Column-Number Company Delete-Selection Direnv
Display-Line-Numbers Display-Time Electric-Indent Electric-Pair Emojify
File-Name-Shadow Font-Lock Global-Anzu Global-Auto-Revert Global-Company
Global-Diff-Hl Global-Display-Line-Numbers Global-Eldoc Global-Emojify
Global-Flycheck Global-Font-Lock Global-Git-Commit Global-Hl-Line Global-Hl-Todo
Global-Undo-Tree Global-Whitespace Ivy Line-Number Mouse-Wheel Org-Recent-Headings
Override-Global Popwin Projectile Recentf Shell-Dirtrack Show-Paren
Straight-Package-Neutering Straight-Use-Package Tex-Pdf Tooltip Transient-Mark
Undo-Tree Which-Key Winner Ws-Butler Ws-Butler-Global Yas Yas-Global```

**Comment by davep** [comment]
I'll do a little more digging here too when I get a moment and see if I can find a way to recreate this. Let's keep this open until we find out the cause one way or another.
